
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('resort_data').del()
    .then(function () {
      return Promise.all([
      	knex('resort_data').insert({resort_name:'Telluride',       api_path:'telluride',       beginner:9, intermediate: 9, advanced: 8, off_piste:	8, tree_skiing: 8, expert: 10, extreme: 9, snow: 8, freshies:	7, uncrowded: 7, slackcountry: 7, lifts: 10, terrain_park: 6, family_friendly:	9, daytime_restaurants: 10, nighttime_restaurants: 9, nightlife: 6, skin_skiout: 10, cost:	4, apres: 6, powderhounds: 9, overall: 10}),
      	knex('resort_data').insert({resort_name:'Beaver Creek',    api_path:'beavercreek',    beginner:9, intermediate: 8, advanced: 8, off_piste:	7, tree_skiing: 6, expert: 6, extreme: 5, snow: 7, freshies:	5, uncrowded: 5, slackcountry: 0, lifts: 9, terrain_park: 6, family_friendly:	9, daytime_restaurants: 7, nighttime_restaurants: 8, nightlife: 5, skin_skiout: 10, cost:	3, apres: 6, powderhounds: 7, overall: 8}),
      	knex('resort_data').insert({resort_name:'Snowmass',        api_path:'snowmass',        beginner:6, intermediate: 10, advanced: 6, off_piste:	9, tree_skiing: 8, expert: 9, extreme: 9, snow: 8, freshies:	6, uncrowded: 7, slackcountry: 0, lifts: 9, terrain_park: 8, family_friendly:	10, daytime_restaurants: 7, nighttime_restaurants: 6, nightlife: 5, skin_skiout: 10, cost:	5, apres: 5, powderhounds: 8, overall: 9}),
      	knex('resort_data').insert({resort_name:'Vail',            api_path:'vail',            beginner:6, intermediate: 7, advanced: 10, off_piste:	10, tree_skiing: 7, expert: 5, extreme: 0, snow: 8, freshies:	5, uncrowded: 4, slackcountry: 6, lifts: 9, terrain_park: 8, family_friendly:	6, daytime_restaurants: 10, nighttime_restaurants: 10, nightlife: 10, skin_skiout: 5, cost:	4, apres: 10, powderhounds: 7, overall: 9}),
      	knex('resort_data').insert({resort_name:'Breckenridge',    api_path:'breck',           beginner:10, intermediate: 8, advanced: 9, off_piste:	9, tree_skiing: 5, expert: 8, extreme: 8, snow: 7, freshies:	4, uncrowded: 2, slackcountry: 0, lifts: 8, terrain_park: 10, family_friendly:	9, daytime_restaurants: 6, nighttime_restaurants: 8, nightlife: 10, skin_skiout: 8, cost:	6, apres: 8, powderhounds: 6, overall: 9}),
	      knex('resort_data').insert({resort_name:'Buttermilk',      api_path:'buttermilk',      beginner:9, intermediate: 6, advanced: 4, off_piste:	4, tree_skiing: 4, expert: 3, extreme: 0, snow: 5, freshies:	6, uncrowded: 8, slackcountry: 0, lifts: 8, terrain_park: 10, family_friendly:	8, daytime_restaurants: 5, nighttime_restaurants: 2, nightlife: 2, skin_skiout: 3, cost:	5, apres: 3, powderhounds: 6, overall: 7}),
        knex('resort_data').insert({resort_name:'Copper Mountain', api_path:'copper',          beginner:10, intermediate: 10, advanced: 7, off_piste:	8, tree_skiing: 6, expert: 6, extreme: 6, snow: 7, freshies:	5, uncrowded: 7, slackcountry: 8, lifts: 8, terrain_park: 8, family_friendly:	10, daytime_restaurants: 8, nighttime_restaurants: 8, nightlife: 7, skin_skiout: 7, cost:	6, apres: 8, powderhounds: 7, overall: 9}),
      	knex('resort_data').insert({resort_name:'Keystone',        api_path:'keystone',        beginner:5, intermediate: 10, advanced: 8, off_piste:	8, tree_skiing: 8, expert: 6, extreme: 0, snow: 6, freshies:	4, uncrowded: 4, slackcountry: 10, lifts: 8, terrain_park: 10, family_friendly:	6, daytime_restaurants: 4, nighttime_restaurants: 8, nightlife: 8, skin_skiout: 2, cost:	6, apres: 6, powderhounds: 6, overall: 8}),
      	knex('resort_data').insert({resort_name:'Aspen Highlands', api_path:'aspen-highlands', beginner:6, intermediate: 7, advanced: 8, off_piste:	8, tree_skiing: 6, expert: 9, extreme: 6, snow: 7, freshies:	6, uncrowded: 8, slackcountry: 0, lifts: 7, terrain_park: 0, family_friendly:	6, daytime_restaurants: 5, nighttime_restaurants: 4, nightlife: 4, skin_skiout: 6, cost:	5, apres: 5, powderhounds: 8, overall: 8}),
      	knex('resort_data').insert({resort_name:'Aspen Mountain',  api_path:'aspen-mountain',  beginner:2, intermediate: 7, advanced: 7, off_piste:	6, tree_skiing: 25, expert: 6, extreme: 4, snow: 7, freshies:	5, uncrowded: 7, slackcountry: 0, lifts: 7, terrain_park: 0, family_friendly:	5, daytime_restaurants: 5, nighttime_restaurants: 10, nightlife: 9, skin_skiout: 4, cost:	4, apres: 8, powderhounds: 7, overall: 7}),
        knex('resort_data').insert({resort_name:'Crested Butte',   api_path:'crested-butte',   beginner:7, intermediate: 7, advanced: 5, off_piste:	8, tree_skiing: 8, expert: 10, extreme: 10, snow: 7, freshies:	8, uncrowded: 8, slackcountry: 0, lifts: 7, terrain_park: 7, family_friendly:	9, daytime_restaurants: 6, nighttime_restaurants: 8, nightlife: 6, skin_skiout: 6, cost:	8, apres: 8, powderhounds: 8, overall: 9}),
      	knex('resort_data').insert({resort_name:'Steamboat',       api_path:'steamboat',       beginner:7, intermediate: 9, advanced: 8, off_piste:	8, tree_skiing: 10, expert: 6, extreme: 4, snow: 8, freshies:	6, uncrowded: 8, slackcountry: 0, lifts: 7, terrain_park: 7, family_friendly:	9, daytime_restaurants: 6, nighttime_restaurants: 7, nightlife: 6, skin_skiout: 7, cost:	6, apres: 6, powderhounds: 8, overall: 9}),
      	knex('resort_data').insert({resort_name:'Winter Park',     api_path:'winter-park',     beginner:7, intermediate: 10, advanced: 6, off_piste:	5, tree_skiing: 6, expert: 4, extreme: 2, snow: 6, freshies:	6, uncrowded: 6, slackcountry: 6, lifts: 8, terrain_park: 6, family_friendly:	8, daytime_restaurants: 8, nighttime_restaurants: 8, nightlife: 7, skin_skiout: 8, cost:	6, apres: 5, powderhounds: 6, overall: 8}),
      	knex('resort_data').insert({resort_name:'Loveland',        api_path:'loveland',        beginner:9, intermediate: 6, advanced: 4, off_piste:	4, tree_skiing: 4, expert: 4, extreme: 4, snow: 7, freshies:	6, uncrowded: 8, slackcountry: 4, lifts: 2, terrain_park: 0, family_friendly:	6, daytime_restaurants: 3, nighttime_restaurants: 0, nightlife: 0, skin_skiout: 0, cost:	9, apres: 3, powderhounds: 6, overall: 6}),
      	knex('resort_data').insert({resort_name:'Arapahoe Basin',  api_path:'abasin',          beginner:4, intermediate: 5, advanced: 6, off_piste:	7, tree_skiing: 4, expert: 6, extreme: 4, snow: 6, freshies:	6, uncrowded: 8, slackcountry: 6, lifts: 5, terrain_park: 6, family_friendly:	2, daytime_restaurants: 5, nighttime_restaurants: 0, nightlife: 0, skin_skiout: 0, cost:	6, apres: 2, powderhounds: 7, overall: 6}),
      	knex('resort_data').insert({resort_name:'Monarch',         api_path:'monarch',         beginner:5, intermediate: 5, advanced: 4, off_piste:	6, tree_skiing: 6, expert: 6, extreme: 6, snow: 7, freshies:	6, uncrowded: 8, slackcountry: 6, lifts: 5, terrain_park: 5, family_friendly:	8, daytime_restaurants: 4, nighttime_restaurants: 4, nightlife: 2, skin_skiout: 0, cost:	9, apres: 4, powderhounds: 8, overall: 7}),
      ]);
    });
};
